name: Common CI - Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    
    - name: Download and install deb packages
      run: |
          sudo apt-get update
          sudo $PWD/install-dependencies.sh

    - name: Node.js Setup
      uses: actions/setup-node@v2
    - name: Installation of Node.js dependencies
      run: npm i